-- ALTER TABLE employers
-- ALTER COLUMN yearly_revenue SET DATA TYPE NUMERIC(10,2);
-- ALTER COLUMN yearly_revenue SET DATA TYPE FLOAT;
-- ALTER COLUMN company_name SET DATA TYPE VARCHAR(100);


ALTER TABLE users
ALTER COLUMN full_name SET DATA TYPE VARCHAR(100);